### ISSUE TITLE
HowTO for HA configs

### ISSUE THREAD

**Issue by aladin2000** [antibill51/Alfawise_SJ-7_HASSIO#1]
HI Antibill51 Great Job ... and 
I plan to use your contributions to include my Alfawise sj7 in my HA instance
But I must admit that I am a little bit confused because I wander how to use the codes and config from your site without a little Tutorials explanation. 
I already know esphome as I already uses lctech to burn them with  esp easy esphome and  tuyaconvert to get  tasmota firmware 
I saw a lot of codes pieces related to HA,do i have to add the code files into custom_components ? 
put the lovelace file inside the lovelace directory of HA ?  or Do I have to split into pieces for each item (script,...)
Do I have to use it into a package ?....

Don't you think that a little HowTo  is missing  - how to put the whole files in a correct configuration  into HA instance 
I hope I could get you help in return of that issue.

**Comment by antibill51** [comment]
Hi.

First, for the esphome part:
Are you using the esphome addon on HA?
Then, place the uart_read_line_sensor.h and uart_test_component.h files in your config/esphome folder
Copy and adapt if necessary the diffuser.yaml part

For the lovelace part, place the diffuser.png file in the config/www/ folder
Install via HACS
custom:vertical-stack-in-card
custom:fan-percent-button-row
custom:paper-buttons-row

Then use the graphics wizard to copy the contents of the card.
(Add card, manual, and paste code)

![image](https://user-images.githubusercontent.com/25085497/197381812-6ae21d26-ac2b-4487-8b52-4e1641dba041.png)

PS : tu parles français?

**Comment by aladin2000** [comment]
Bonjour
Merci pour ces explications c'est très sympa
En effet c'est ce que j'ai fait pour esphome et je n'ai pas encore flashé le esp du alfawise
mais j'avais un doute sur la partie Lovelace a mettre ou non dans ui-lovelace.yaml ou pas

Une autre question pour la partie flashage ...
Tu le fais depuis esphome ? mais peut on le faire avec tasmota ? Ou tuyauconvert ?

Cordialement
Aladin

23 oct. 2022 10:19:11 antibill51 ***@***.***>:

**Comment by antibill51** [comment]
L'addon esphome de home assistant peut flasher, mais d'autres outils également.

![Screenshot_20221023-170925_Home Assistant~2.png](https://user-images.githubusercontent.com/25085497/197399919-1dcece3c-5b7d-4b68-ab36-5f19c63af3b8.png) 

J'avais d'abord tenté le devoloppement en utilisant tasmota, mais ça manquait de fiabilité à mon goût.

**Comment by aladin2000** [comment]
Je rencontre un soucis lors de la phase install
La validate est ok
As tu une idée sur la cause ?
Voir image
[cid:eu.faircode.email.11307]

23 oct. 2022 17:10:33 antibill51 ***@***.***>:

**Comment by aladin2000** [comment]
J'ai corrigé mon pb  j avais une ancienne version de esphome

23 oct. 2022 20:02:56 Aladin ***@***.***>:
